module.exports = {
  projects: {
    Parabol: {
      schemaPath: './schema.graphql',
      name: 'Parabol GraphQL Schema',
      includes: ['*'],
      excludes: ['githubSchema.graphql', './packages/client/utils/githubQueries']
    },
    GitHub: {
      schemaPath: './packages/server/utils/githubSchema.graphql',
      name: 'GitHub GraphQL Schema',
      includes: ['./packages/client/utils/githubQueries/*.graphql'],
      extensions: {
        schemaTypesPath: 'packages/client/utils/githubQueries/types'
      }
    }
  }
}
