
version: "3.7"

services:
  db:
    image: rethinkdb:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "29015:29015"
      - "28015:28015"
    volumes:
      - rethink-data:/data
    networks:
      - parabol-network
  postgres:
    build:
      context: "../packages/server/postgres"
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "5432:5432"
    volumes:
      - "../packages/server/postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - "postgres-data:/data"
    command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"
    networks:
      - parabol-network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    depends_on:
      - postgres
    env_file: ../.env
    volumes:
       - "pgadmin-data:/var/lib/pgadmin"
    ports:
      - "5050:80"
    networks:
      - parabol-network
    restart: unless-stopped
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - parabol-network
networks:
  parabol-network:
volumes:
  redis-data: {}
  rethink-data: {}
  postgres-data: {}
  pgadmin-data: {}
