version: "3.7"

services:
  datadog:
    image: gcr.io/datadoghq/agent:7
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "8126:8126"
    networks:
      - parabol-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  db:
    image: rethinkdb:2.4.2
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "29015:29015"
      - "28015:28015"
    volumes:
      - rethink-data:/data
    networks:
      - parabol-network
  postgres:
    build:
      context: "../packages/server/postgres"
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "5432:5432"
    volumes:
      - "../packages/server/postgres/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - "postgres-data:/var/lib/postgresql/data"
    command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"
    networks:
      - parabol-network
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    env_file: ../.env
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"
    ports:
      - "5050:80"
    networks:
      - parabol-network
    restart: unless-stopped
  redis:
    image: bitnami/redis:7.0-debian-11
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=''
      - REDIS_TLS_ENABLED=no
      - REDIS_TLS_AUTH_CLIENTS=no
      - REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      - REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      - REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/redisCA.crt
    ports:
      - "6379:6379"
    volumes:
      - bitnami-redis-data:/bitnami/redis/data
      - ../certs:/opt/bitnami/redis/certs
    networks:
      - parabol-network
  redis-commander:
    container_name: redis_commander
    image: ghcr.io/joeferner/redis-commander:latest
    hostname: redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"
    networks:
      parabol-network:
networks:
  parabol-network:
volumes:
  bitnami-redis-data: {}
  rethink-data: {}
  postgres-data: {}
  pgadmin-data: {}
