name: Update Snyk PR to add yarn.lock

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-snyk-pr:
    if: contains(github.event.pull_request.title.toLowerCase(), '[snyk]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}  # This token is provided by Actions, no need to create one

      - name: Install dependencies
        run: yarn install

      - name: Commit yarn.lock to the PR branch
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add yarn.lock
          git commit -m "Update yarn.lock" || echo "No changes to commit"
          git push

